version: "3.3"
services:

  nginx:
    image: nginx:1.18.0
    depends_on:
      - db
      - sonarqube
      - nexus
    ports:
      - "8585:8081"
      - "8586:8082"
      - "5000:5000"
    volumes: 
      - ${PWD}/nginx/certs:/certs
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:3.37.0
    ports:
      - "8081"
    volumes: 
      - ./nexus-data:/nexus-data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:7.9.5-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "9000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:2.278
    privileged: true
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080" # Web Server
      - "50000" # Remote Java (Jira) API


volumes:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
  jenkins_data:
